mysql:

CREATE TABLE IF NOT EXISTS Tracker (entryID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, date VARCHAR(32) NOT NULL, ppm INT NOT NULL, ph DOUBLE NOT NULL, note TEXT)

CREATE TABLES IF NOT EXISTS Temps (tempID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, address VARCHAR(32) NOT NULL, temp FLOAT, time TIMESTAMP)

CREATE TABLES IF NOT EXISTS Humid (humidID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, humid FLOAT, time TIMESTAMP)

CREATE TABLES IF NOT EXISTS Relay (relayUID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, mode INT)

CREATE TABLES IF NOT EXISTS Timer (timerID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, relayID INT, onTime VARCHAR(32), offTime VARCHAR(32))

CREATE TABLES IF NOT EXISTS Target (targetID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, relayID INT, target DOUBLE)

CREATE TABLES IF NOT EXISTS



sqlite:

CREATE TABLE IF NOT EXISTS 'Tracker' ('EntryID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'Date' TEXT NOT NULL, 'PPM' INTEGER NOT NULL, 'PH' REAL NOT NULL, 'TempHi' INTEGER NOT NULL, 'TempLo' INTEGER NOT NULL, 'Humid' INTEGER NOT NULL, 'Note' TEXT)

CREATE TABLE IF NOT EXISTS 'Image' ('ImageID' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'EntryID' INTEGER NOT NULL, 'IMG' BLOB NOT NULL)