#!/bin/bash

#script to keep number of images generated by motion under control..
# remove images older than 3 days

find /var/www/motion/camera1 -mtime +3 -type f -exec rm -rf {} \;
find /var/www/motion/camera2 -mtime +3 -type f -exec rm -rf {} \;

exit
